### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by bobholt** [donasaur/http-proxy-rules#10]
I'd like to use `http-proxy-rules` in a project. Unfortunately without a license, it's not legal (at least in the U.S.) to reproduce, distribute, or create derivative works of `http-proxy-rules`.

Check out GitHub's docs: https://help.github.com/articles/licensing-a-repository/, and I'm happy to answer any questions.

**Comment by donasaur** [comment]
Kk, added. Thanks!
