### ISSUE TITLE
Is there a way to change rules without restarting proxy ?

### ISSUE THREAD

**Issue by NoxWorld258** [donasaur/http-proxy-rules#11]
Hi, 

Well everything is in the title, is there a way i can change the rules dynamically (i will get them from MySQL i think) , and make / write the changes without restarting the proxy ?

Anyway, good job & nice code :D

**Comment by donasaur** [comment]
Thanks. Each HttpProxyRules instance has a rules property that you can edit. That should allow you to change rules dynamically. You can also create additional HttpProxyRules instances corresponding to different rulesets if you don't want to mutate the instances.
